pridetiFinanceManager
BanisBT/2021-03-13-carParking pull request #1
Opened 2021-03-16 19:29 UTC by BanisBT

Jei pastabos kartotusi kaip Biudzeto uzdavinyje tai juos padarysiu kai issiaiskinsiu kas ten negerai

2021-03-16 19:40 UTC, Elvinasl requested changes

2021-03-16 19:40 UTC, Elvinasl commented on src/main/java/org/tomasBarauskas/App.java
> +        }
O kodel negalime iskelti sito is main i kita servisa?

2021-03-16 19:40 UTC, Elvinasl commented on src/main/java/org/tomasBarauskas/modul/parking/ParkingCity.java
>      VILNIU(ParkingZone.VILNIUS_GREEN_ZONE,ParkingZone.VILNIUS_RED_ZONE,ParkingZone.VILNIUS_BLUE_ZONE),
labai sudetingas enum'as. Ka nori cia padaryti? Gal geriau kurti objekta?

2021-03-16 19:40 UTC, Elvinasl commented on src/main/java/org/tomasBarauskas/service/financeManager/FinanceManagerImpl.java
> +        float ticketCost = (float) ticket.getParkingTime().getHourInDoubleValue() * ticket.getParkingZone().getCostPerHour();
kodel float? Pagalvok apie BigDecimal panaudojima

2021-03-16 19:40 UTC, Elvinasl commented on src/main/java/org/tomasBarauskas/service/financeManager/FinanceManagerImpl.java
> +        }
Cia galima supaprastinti koda, jeigu apsuksi salyga. Tada ir boolean nereikes.

2021-03-16 19:59 UTC, BanisBT commented on src/main/java/org/tomasBarauskas/App.java
> +        }
cia testavau tiesiog ar veikia pinigu nuskaitymas, tikrinimas ar pakanka lesu ir parkingTicket sukurimas, daug eiluciu issitrins

2021-03-16 20:02 UTC, BanisBT commented on src/main/java/org/tomasBarauskas/modul/parking/ParkingCity.java
>      VILNIU(ParkingZone.VILNIUS_GREEN_ZONE,ParkingZone.VILNIUS_RED_ZONE,ParkingZone.VILNIUS_BLUE_ZONE),
Toki enuma kuriau del sito metodo
private ParkingZone chooseZoneForParking(ParkingCity chosenCity) main 355 eilute
kazkaip kitaip pabandysiu pergalvot

2021-03-16 20:03 UTC, BanisBT commented on src/main/java/org/tomasBarauskas/service/financeManager/FinanceManagerImpl.java
> +        float ticketCost = (float) ticket.getParkingTime().getHourInDoubleValue() * ticket.getParkingZone().getCostPerHour();
ok, reiks panagrinet ji, nesu dar susidures su BigDecimal

2021-03-16 20:08 UTC, BanisBT commented on src/main/java/org/tomasBarauskas/service/financeManager/FinanceManagerImpl.java
> +        }
geras. Pakeisiu

2021-03-17 17:57 UTC, pavelvrublevskij requested changes
Dar servisu neziurejau, bandau isigilinti.Tad veliau feedback pateiksiu

2021-03-17 17:57 UTC, pavelvrublevskij commented on src/main/java/org/tomasBarauskas/modul/CompanyAccount.java
> +    private float companyAccount;
Kodel companyAccount float? Man pavadinimas asocijojasi ne su slenkanciu kableliu o su String duomenu tipu. Kaip pvz. bank account

2021-03-17 17:57 UTC, pavelvrublevskij commented on src/main/java/org/tomasBarauskas/modul/CompanyAccount.java
> +package org.tomasBarauskas.modul;
model o ne modul :D

2021-03-17 17:57 UTC, pavelvrublevskij commented on src/main/java/org/tomasBarauskas/modul/CompanyAccount.java
> +    }
Noretusi matyti get ir poto set (eileskumas klases kintamajam).

2021-03-17 17:57 UTC, pavelvrublevskij commented on src/main/java/org/tomasBarauskas/modul/user/User.java
>  public class User {
Jei klases kintamieji inicializuojami konstruktoriuje tai padarom po final raktazodziu

2021-03-17 17:57 UTC, pavelvrublevskij commented on src/main/java/org/tomasBarauskas/App.java
> +package org.tomasBarauskas;
Package names should comply with a naming convention

package org.exAmple; // Noncompliant
package org.example; // Compliant

2021-03-17 17:57 UTC, pavelvrublevskij commented on src/main/java/org/tomasBarauskas/modul/parking/ParkingZone.java
>  public enum ParkingZone {
As gal kiekvienam miestui sukurciau atskirus enum ir nereiktu to ParkingZone.

O pati ParkingCity bandyciau daryti generic klase kuri priima enum (skirtingu miestu) kaip tipa. Sudetingas variantas. Pasiskaityti https://stackoverflow.com/questions/15366375/generics-and-class-extends-enum-enumset-allofclass-vs-class-getenumcons arba https://puredanger.github.io/tech.puredanger.com/2006/10/25/fun-with-generics-and-enums/

2021-03-18 18:05 UTC, BanisBT commented on src/main/java/org/tomasBarauskas/modul/CompanyAccount.java
> +    private float companyAccount;
Cia yra imones saskaita ne kaip jos nr, o kaip vieta kur saugomi pinigai, del to String gal nelb

2021-03-18 18:40 UTC, merged